import { Itinerary } from "@/types";
import { formatDistance, formatDuration } from "@/services/routing";

export function exportItineraryJSON(itinerary: Itinerary): void {
  const blob = new Blob([JSON.stringify(itinerary, null, 2)], {
    type: "application/json",
  });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `wayvora-itinerary-${itinerary.name.replace(/\s+/g, "-")}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function exportItineraryPDF(itinerary: Itinerary): void {
  const { route } = itinerary;

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8" />
      <title>Wayvora Itinerary — ${itinerary.name}</title>
      <style>
        @import url("https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600;700&family=DM+Sans:wght@400;500;600&display=swap");
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
          font-family: 'DM Sans', sans-serif;
          color: #1e293b;
          padding: 48px;
          background: #fff;
          line-height: 1.5;
        }
        .header {
          border-bottom: 3px solid #0891b2;
          padding-bottom: 24px;
          margin-bottom: 32px;
        }
        .header h1 {
          font-family: 'Playfair Display', serif;
          font-size: 32px;
          font-weight: 700;
          color: #0e7490;
        }
        .header .meta {
          font-size: 13px;
          color: #64748b;
          margin-top: 6px;
        }
        .summary-row {
          display: flex;
          gap: 32px;
          background: #ecfeff;
          border-radius: 12px;
          padding: 18px 24px;
          margin-bottom: 32px;
        }
        .summary-item { flex: 1; }
        .summary-item .label {
          font-size: 11px;
          text-transform: uppercase;
          letter-spacing: 1px;
          color: #0891b2;
          font-weight: 600;
        }
        .summary-item .value {
          font-size: 20px;
          font-weight: 600;
          color: #0e7490;
          margin-top: 2px;
        }
        .stop {
          display: flex;
          gap: 20px;
          margin-bottom: 24px;
          align-items: flex-start;
        }
        .stop-number {
          min-width: 36px;
          height: 36px;
          border-radius: 50%;
          background: linear-gradient(135deg, #06b6d4, #0891b2);
          color: white;
          display: flex;
          align-items: center;
          justify-content: center;
          font-weight: 700;
          font-size: 15px;
          flex-shrink: 0;
        }
        .stop-content h3 { font-size: 16px; font-weight: 600; color: #0f172a; }
        .stop-content p { font-size: 13px; color: #64748b; margin-top: 2px; }
        .badge-row { display: flex; gap: 8px; margin-top: 6px; }
        .badge {
          display: inline-block;
          padding: 2px 10px;
          border-radius: 20px;
          font-size: 11px;
          font-weight: 600;
        }
        .badge-cat { background: #cffafe; color: #0e7490; }
        .badge-type { background: #f1f5f9; color: #475569; }
        .connector {
          border-left: 2px dashed #a5f3fc;
          margin-left: 17px;
          height: 20px;
        }
        .notes-section {
          margin-top: 32px;
          border-top: 1px solid #e2e8f0;
          padding-top: 20px;
        }
        .notes-section h2 { font-size: 14px; font-weight: 600; color: #475569; margin-bottom: 8px; }
        .notes-section p { font-size: 13px; color: #64748b; }
        .footer {
          margin-top: 48px;
          padding-top: 16px;
          border-top: 1px solid #e2e8f0;
          font-size: 11px;
          color: #94a3b8;
          text-align: center;
        }
        @media print {
          body { padding: 32px; }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${itinerary.name}</h1>
        <div class="meta">Generated by Wayvora &middot; ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</div>
      </div>
      <div class="summary-row">
        <div class="summary-item">
          <div class="label">Total Distance</div>
          <div class="value">${formatDistance(route.totalDistance)}</div>
        </div>
        <div class="summary-item">
          <div class="label">Est. Duration</div>
          <div class="value">${formatDuration(route.totalDuration)}</div>
        </div>
        <div class="summary-item">
          <div class="label">Stops</div>
          <div class="value">${route.pois.length}</div>
        </div>
        <div class="summary-item">
          <div class="label">Mode</div>
          <div class="value" style="text-transform:capitalize">${route.transportMode === "walk" ? "Walking" : route.transportMode === "bike" ? "Cycling" : route.transportMode === "car" ? "Driving" : "Transit"}</div>
        </div>
      </div>
      ${route.pois
        .map(
          (poi, i) =>
            `<div class="stop">
              <div class="stop-number">${i + 1}</div>
              <div class="stop-content">
                <h3>${poi.name}</h3>
                <p>${poi.address}</p>
                <div class="badge-row">
                  <span class="badge badge-cat">${poi.category}</span>
                  ${poi.openingHours ? `<span class="badge badge-type">⏰ ${poi.openingHours}</span>` : ""}
                </div>
              </div>
            </div>
            ${i < route.pois.length - 1 ? '<div class="connector"></div>' : ""}`
        )
        .join("")}
      ${itinerary.notes ? `<div class="notes-section"><h2>Notes</h2><p>${itinerary.notes}</p></div>` : ""}
      <div class="footer">Wayvora — Smart Local Explorer &amp; Travel Planner</div>
    </body>
    </html>
  `;

  const printWindow = window.open("", "_blank");
  if (!printWindow) return;

  printWindow.document.write(html);
  printWindow.document.close();

  printWindow.onload = () => {
    printWindow.focus();
    printWindow.print();
  };
}
